### ISSUE TITLE
loki installation incomplete/failed

### ISSUE THREAD

**Issue by hjri** [YunoHost-Apps/loki_ynh#26]
### Describe the bug

Loki does not start, service is failed. Root cause:

`/var/www/loki/merge_yaml.sh: No such file or directory`

### Context

- Hardware: Hetzner Cloud VPS
- YunoHost version: 11.2.9.1 (stable).
- I have access to my server: SSH+webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.8.4~ynh2

### Steps to reproduce

- install Loki + Promtail app

### Expected behavior

Installation is complete and loki is running

### Logs

Loki.service fails with
`/var/www/loki/merge_yaml.sh: No such file or directory`

and so does loki-promtail

**Comment by hjri** [comment]
this could be fixed by running (on amd64 but possibly on the archs as well)
```
cd /var/www/loki/ 
wget https://raw.githubusercontent.com/YunoHost-Apps/loki_ynh/master/sources/extra_files/loki-amd64/merge_yaml.sh
chmod +x merge_yaml.sh 
chown loki:www-data merge_yaml.sh
```

**Comment by fflorent** [comment]
@Salamandar This seems to be due to this PR: #23 
 - before that PR, I can install loki successfully and `systemctl status loki` shows that the service is working
 - after that PR, the above error exists

Unless I am wrong.

I am grateful for the PR, but I felt a bit upset by the merge without giving me time to review the change, whereas I am mentioned as the [only maintainer](https://github.com/YunoHost-Apps/loki_ynh/blob/93d1bfa877a55356eedf6d333400c7dc36dbd535/manifest.toml#L12) of the package. 

I noticed you were not the only person to bypass my review. If there are any reason for hurrying merging this PR, please let me know them.

If there are none, there is no worry to have. In the future, we can agree to some process to follow.

I would appreciate that if you fix the issue, you make a PR and give me time to review the change (or I can fix myself, I don't mind). If I take time (like 2 weeks) or if there exist risks for waiting (say for security reasons), I would agree that you can legitimately bypass my review (even if this introduces new issues).

What do you think?

Thanks in advance.

And again, despite what I say above, thanks for you work on migrating to the manifest v2
